
version: 2

models:
    - name: stg_listings
      columns:
          - name: listing_id
            tests:
                - unique
                - not_null

#          - name: host_id
#            tests:
#                - unique
